services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
    - ./backend/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54322:5432"
  game:
    depends_on:
      - postgres
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:80"
  bot:
    depends_on:
      - game
      - postgres
    build: ./bot
    env_file:
      - ./bot/.env
      
